name: retry_build_api
description: A new Flutter project.

publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdf: ^20.2.36
  path_provider: ^2.0.11
  open_file: ^3.2.1
  nb_utils: ^4.6.10
  #help to api data get {
  http:
  json_annotation: ^4.6.0
  # }
  hexcolor: ^2.0.7
  # webview_flutter: ^3.0.4
  webview_flutter: ^4.0.0
  flutter_webview_plugin: ^0.4.0
  provider:

  cupertino_icons: ^1.0.2
  paytm_allinonesdk: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #help to api data get {
  build_runner: ^2.2.1
  json_serializable: ^6.3.2
  # }
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/home.jpg
    - assets/appIconAndroid.png